export const mockProducts = [
  {
    productId: 1,
    title: "Tênis Drip Classic",
    images: [
      {
        src: "https://raw.githubusercontent.com/digitalcollegebr/projeto-digital-store/main/public/produc-image-1.jpeg",
        alt: "Tênis Drip Classic - Frente",
      },
    ],
    description: "Tênis casual com design moderno e confortável.",
    assessment: 4.2,
    model: "Classic 01",
    mark: "Drip",
    ref: "DR001",
    realPrice: "399.90",
    descontedPrice: "329.90",
    sizes: ["37", "38", "39", "40"],
    colors: ["#000000", "#555555"],
  },
  {
    productId: 2,
    title: "Tênis Pulse Urban",
    images: [
      {
        src: "https://raw.githubusercontent.com/digitalcollegebr/projeto-digital-store/main/public/produc-image-2.jpeg",
        alt: "Tênis Pulse Urban - Frente",
      },
    ],
    description: "Ideal para caminhada e uso urbano, leve e estiloso.",
    assessment: 3.8,
    model: "Urban 202",
    mark: "Pulse",
    ref: "PU202",
    realPrice: "449.99",
    descontedPrice: "379.99",
    sizes: ["38", "39", "40", "42"],
    colors: ["#222222", "#888888"],
  },
  {
    productId: 3,
    title: "Tênis Galaxy Pro",
    images: [
      {
        src: "https://raw.githubusercontent.com/digitalcollegebr/projeto-digital-store/main/public/produc-image-3.jpeg",
        alt: "Tênis Galaxy Pro - Lateral",
      },
    ],
    description: "Performance esportiva com máximo conforto e estabilidade.",
    assessment: 4.5,
    model: "Galaxy Pro",
    mark: "SpeedX",
    ref: "SPX301",
    realPrice: "599.90",
    descontedPrice: "519.90",
    sizes: ["39", "40", "41", "43"],
    colors: ["#0033FF", "#000000"],
  },
  {
    productId: 4,
    title: "Tênis Vision Street",
    images: [
      {
        src: "https://raw.githubusercontent.com/digitalcollegebr/projeto-digital-store/main/public/produc-image-4.jpeg",
        alt: "Tênis Vision Street - Vista superior",
      },
    ],
    description: "Estilo urbano com material resistente e confortável.",
    assessment: 4.1,
    model: "Vision Street",
    mark: "Urban Walk",
    ref: "UW541",
    realPrice: "369.99",
    descontedPrice: "299.99",
    sizes: ["36", "37", "38", "39"],
    colors: ["#FFFFFF", "#333333"],
  },
  {
    productId: 5,
    title: "Tênis Impact Run",
    images: [
      {
        src: "https://raw.githubusercontent.com/digitalcollegebr/projeto-digital-store/main/public/produc-image-5.jpeg",
        alt: "Tênis Impact Run - Lado",
      },
    ],
    description: "Perfeito para corridas leves e treinos diários.",
    assessment: 4.6,
    model: "Impact 500",
    mark: "Runner Pro",
    ref: "RP500",
    realPrice: "489.90",
    descontedPrice: "419.90",
    sizes: ["39", "40", "41", "42", "43"],
    colors: ["#FF0000", "#111111"],
  },
  {
    productId: 6,
    title: "Tênis Casual Color",
    images: [
      {
        src: "https://raw.githubusercontent.com/digitalcollegebr/projeto-digital-store/main/public/product-thumb-1.jpeg",
        alt: "Tênis Casual Color - Colorido",
      },
    ],
    description: "Tênis casual vibrante para quem gosta de cor e estilo.",
    assessment: 3.9,
    model: "Color 101",
    mark: "Style",
    ref: "ST101",
    realPrice: "299.90",
    descontedPrice: "249.90",
    sizes: ["35", "36", "37", "38"],
    colors: ["#FF69B4", "#00FFFF", "#FFA500"],
  },
  {
    productId: 7,
    title: "Tênis Sport Wave",
    images: [
      {
        src: "https://raw.githubusercontent.com/digitalcollegebr/projeto-digital-store/main/public/product-thumb-2.jpeg",
        alt: "Tênis Sport Wave - Perfil",
      },
    ],
    description: "Tênis esportivo com tecnologia de amortecimento.",
    assessment: 4.7,
    model: "Wave 202",
    mark: "Sport Line",
    ref: "SL202",
    realPrice: "559.90",
    descontedPrice: "499.90",
    sizes: ["38", "39", "41", "42"],
    colors: ["#0000FF", "#A9A9A9"],
  },
  {
    productId: 8,
    title: "Tênis Eco Move",
    images: [
      {
        src: "https://raw.githubusercontent.com/digitalcollegebr/projeto-digital-store/main/public/product-thumb-3.jpeg",
        alt: "Tênis Eco Move - Sustentável",
      },
    ],
    description: "Produzido com materiais recicláveis, leve e durável.",
    assessment: 4.3,
    model: "Eco Move 3",
    mark: "GreenStep",
    ref: "GS003",
    realPrice: "429.90",
    descontedPrice: "369.90",
    sizes: ["37", "38", "39", "40", "41"],
    colors: ["#228B22", "#A0522D"],
  },
  {
    productId: 9,
    title: "Tênis Night Runner",
    images: [
      {
        src: "https://raw.githubusercontent.com/digitalcollegebr/projeto-digital-store/main/public/home-slide-1.jpeg",
        alt: "Tênis Night Runner - Noturno",
      },
    ],
    description: "Tênis com detalhes refletivos para corridas noturnas.",
    assessment: 4.0,
    model: "Night Run",
    mark: "FlashRun",
    ref: "FR001",
    realPrice: "479.90",
    descontedPrice: "419.90",
    sizes: ["39", "40", "42", "43"],
    colors: ["#000000", "#444444"],
  },
  {
    productId: 10,
    title: "Tênis Breeze Light",
    images: [
      {
        src: "https://raw.githubusercontent.com/digitalcollegebr/projeto-digital-store/main/public/home-slide-2.jpeg",
        alt: "Tênis Breeze Light - Arejado",
      },
    ],
    description: "Super leve, ideal para o verão ou caminhadas longas.",
    assessment: 3.7,
    model: "Breeze Light",
    mark: "WalkFree",
    ref: "WF102",
    realPrice: "349.90",
    descontedPrice: "289.90",
    sizes: ["36", "37", "38", "39", "40"],
    colors: ["#F5F5DC", "#FFE4B5"],
  },
];

export const productsPromotion = [
  {
    productId: 1,
    descPromotion: "Tênis Drip Classic ",
    src: "https://raw.githubusercontent.com/digitalcollegebr/projeto-digital-store/main/public/produc-image-1.jpeg",
    descProduct: "Tênis casual com design moderno e confortável.",
  },
  {
    productId: 2,
    descPromotion: "Tênis Pulse Urban ",
    src: "https://raw.githubusercontent.com/digitalcollegebr/projeto-digital-store/main/public/produc-image-2.jpeg",
    descProduct: "Ideal para caminhada e uso urbano, leve e estiloso.",
  },
  {
    productId: 3,
    descPromotion: "Tênis Galaxy Pro ",
    src: "https://raw.githubusercontent.com/digitalcollegebr/projeto-digital-store/main/public/produc-image-3.jpeg",
    descProduct: "Performance esportiva com máximo conforto e estabilidade.",
  },
  {
    productId: 4,
    descPromotion: "Tênis Vision Street ",
    src: "https://raw.githubusercontent.com/digitalcollegebr/projeto-digital-store/main/public/produc-image-4.jpeg",
    descProduct: "Estilo urbano com material resistente e confortável.",
  },
  {
    productId: 5,
    descPromotion: "Tênis Impact Run ",
    src: "https://raw.githubusercontent.com/digitalcollegebr/projeto-digital-store/main/public/produc-image-5.jpeg",
    descProduct: "Perfeito para corridas leves e treinos diários.",
  },
];
